### ISSUE TITLE
Mimic table seating for more intuitive UX

### ISSUE THREAD

**Issue by GustaMagik** [Zomis/Games#50]
E.g. If you are player two in a four-player game you would like to have the players situated:
3 4 1
   2
Rather than how it is now:
1 3 4
   2

**Comment by Motsols** [comment]
I would like to move play are there. So it is:
1 2 3 4

When it becomes another players turn it can highlight that box more and show "Players is choosing an action".
When it is your turn it expands the area to accomodate the actions you can do.

**Comment by Zomis** [comment]
@GustaMagik's suggestion can be applied quite easily using computed properties in Vue. Add a `othersPlayers` or something property that first adds players that comes after you, and then the players that comes before you, and use that instead of the `players` property in the `v-for` loop.

@Motsols' suggestions is a bit more tricky but could help with saving vertical space, but it might need some discussion if it should be the way to go.

**Comment by Motsols** [comment]
My suggestion wasn't made with the intention of saving space but rather as a way of making it clearer whoms turn it is.
