### ISSUE TITLE
Watching the game as a guest is confusing

### ISSUE THREAD

**Issue by Motsols** [Zomis/Games#59]
I am every player. Very confusing.

This is giving me multiple personality disorder.
![image](https://user-images.githubusercontent.com/694935/81220745-1bccaa00-8fe2-11ea-96ad-37427caf9640.png)

**Comment by Zomis** [comment]
This can be fixed by modifying the view section of `HanabiGame.kt` and/or the template section of `Hanabi.vue`

One way might be to simply change the text "You" for observers to "Current Player"? But then the client needs to know that you are just an observer, which it can be told but is currently not available within the `Hanabi` component. For players it uses `view.hand.index` which it receives from the server and can therefore display the proper hand.

**Comment by Zomis** [comment]
Opinions about how to fix this wanted.

**Comment by Zomis** [comment]
How about allowing the observer to choose from which perspective to watch? The same principle could also be applied to watching replays, and to playing games in local mode.

**Comment by GustaMagik** [comment]
I think making a display mode with an omnipotent view is nice. I.e, all players are displayed side by side on the same row (no active player).

**Comment by Zomis** [comment]
@GustaMagik So simply removing the bottom panel then? Should be quite easy to accomplish :)
